### ISSUE TITLE
ImageIO thread-safety error

### ISSUE THREAD

**Issue by scarf005** [LotuxPunk/Nicephore#19]
```
[22/01/2022 00:25:08 AM] [Thread-29/INFO] [STDERR]: java.awt.HeadlessException
[22/01/2022 00:25:08 AM] [Thread-29/INFO] [STDERR]: 	at java.desktop/sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:216)
[22/01/2022 00:25:08 AM] [Thread-29/INFO] [STDERR]: 	at com.vandendaelen.nicephore.util.CopyImageToClipBoard.copyImage(CopyImageToClipBoard.java:36)
[22/01/2022 00:25:08 AM] [Thread-29/INFO] [STDERR]: 	at com.vandendaelen.nicephore.util.CopyImageToClipBoard.copyLastScreenshot(CopyImageToClipBoard.java:50)
[22/01/2022 00:25:08 AM] [Thread-29/INFO] [STDERR]: 	at com.vandendaelen.nicephore.thread.JPEGThread.run(JPEGThread.java:99)
```
probably because of some optimization mod i've been using...

**Comment by PaintNinja** [comment]
Try using the latest Temurin or Azul Zulu JDK and let us know if that helps

**Comment by LotuxPunk** [comment]
Hey ! This could be solved with this beta version of the mod : https://www.curseforge.com/minecraft/mc-mods/nicephore/files/3645334
